#!/usr/bin/env bash
set -euo pipefail

# ─── NextBazar: Local Supabase Setup ─────────────────────────────────────────
# This script sets up a free local Supabase instance so you can develop
# without touching production data.
#
# Prerequisites:
#   1. Docker Desktop installed and running  (https://docker.com)
#   2. Supabase CLI installed:  npm install -g supabase
#
# Usage:
#   chmod +x scripts/setup-local-supabase.sh
#   ./scripts/setup-local-supabase.sh
# ─────────────────────────────────────────────────────────────────────────────

PROJECT_REF="giseotbdmhdsxgjilrqk"
ENV_FILE=".env.local"
ENV_BACKUP=".env.local.prod-backup"

echo ""
echo "🚀 NextBazar — Local Supabase Setup"
echo "──────────────────────────────────────"

# ── Check prerequisites ──────────────────────────────────────────────────────

if ! command -v docker &>/dev/null; then
  echo "❌ Docker is not installed. Please install Docker Desktop first:"
  echo "   https://www.docker.com/products/docker-desktop"
  exit 1
fi

if ! docker info &>/dev/null 2>&1; then
  echo "❌ Docker is not running. Please start Docker Desktop and try again."
  exit 1
fi

if ! command -v supabase &>/dev/null; then
  echo "📦 Installing Supabase CLI..."
  npm install -g supabase
fi

echo "✅ Prerequisites met"
echo ""

# ── Initialize Supabase (if not already) ─────────────────────────────────────

if [ ! -f "supabase/config.toml" ]; then
  echo "📁 Initializing Supabase in project..."
  supabase init
else
  echo "📁 Supabase already initialized"
fi

# ── Link to production project ───────────────────────────────────────────────

echo ""
echo "🔗 Linking to production project (${PROJECT_REF})..."
echo "   You'll be prompted for your database password."
supabase link --project-ref "$PROJECT_REF"

# ── Pull schema from production ──────────────────────────────────────────────

echo ""
echo "📥 Pulling schema and migrations from production..."
supabase db pull

# ── Start local Supabase ─────────────────────────────────────────────────────

echo ""
echo "🐳 Starting local Supabase (this may take a minute on first run)..."
supabase start

# ── Capture local credentials ────────────────────────────────────────────────

echo ""
echo "🔑 Fetching local credentials..."

LOCAL_API_URL=$(supabase status --output json | grep -o '"API URL": "[^"]*"' | cut -d'"' -f4 2>/dev/null || supabase status | grep "API URL" | awk '{print $NF}')
LOCAL_ANON_KEY=$(supabase status --output json | grep -o '"anon key": "[^"]*"' | cut -d'"' -f4 2>/dev/null || supabase status | grep "anon key" | awk '{print $NF}')
LOCAL_SERVICE_KEY=$(supabase status --output json | grep -o '"service_role key": "[^"]*"' | cut -d'"' -f4 2>/dev/null || supabase status | grep "service_role key" | awk '{print $NF}')
LOCAL_STUDIO_URL=$(supabase status --output json | grep -o '"Studio URL": "[^"]*"' | cut -d'"' -f4 2>/dev/null || supabase status | grep "Studio URL" | awk '{print $NF}')

if [ -z "$LOCAL_API_URL" ] || [ -z "$LOCAL_ANON_KEY" ]; then
  echo ""
  echo "⚠️  Could not auto-detect local credentials. Run 'supabase status' and"
  echo "   update your .env.local manually with the values shown."
  exit 1
fi

# ── Back up existing .env.local and swap to local credentials ────────────────

if [ -f "$ENV_FILE" ]; then
  echo ""
  echo "💾 Backing up current ${ENV_FILE} → ${ENV_BACKUP}"
  cp "$ENV_FILE" "$ENV_BACKUP"
fi

# Write the local env file (preserving any non-Supabase vars from the backup)
if [ -f "$ENV_BACKUP" ]; then
  # Keep lines that aren't Supabase-related
  grep -v -E "^(NEXT_PUBLIC_SUPABASE_URL|NEXT_PUBLIC_SUPABASE_ANON_KEY|SUPABASE_SERVICE_ROLE_KEY)=" "$ENV_BACKUP" > "$ENV_FILE.tmp" || true
  mv "$ENV_FILE.tmp" "$ENV_FILE"
else
  : > "$ENV_FILE"
fi

cat >> "$ENV_FILE" <<EOF

# ── Local Supabase (generated by setup-local-supabase.sh) ──
NEXT_PUBLIC_SUPABASE_URL=${LOCAL_API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${LOCAL_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${LOCAL_SERVICE_KEY}
EOF

# ── Done! ────────────────────────────────────────────────────────────────────

echo ""
echo "──────────────────────────────────────"
echo "✅ Local Supabase is running!"
echo ""
echo "   API URL:    ${LOCAL_API_URL}"
echo "   Studio:     ${LOCAL_STUDIO_URL}"
echo "   Anon Key:   ${LOCAL_ANON_KEY:0:20}..."
echo ""
echo "   Your .env.local has been updated to point to the local instance."
echo "   Your production .env.local is backed up at: ${ENV_BACKUP}"
echo ""
echo "📌 Useful commands:"
echo "   supabase status       — Check local services"
echo "   supabase stop         — Stop local Supabase"
echo "   supabase db reset     — Reset DB to clean schema"
echo ""
echo "🔄 To switch back to production:"
echo "   cp ${ENV_BACKUP} ${ENV_FILE}"
echo ""
echo "🌱 To seed with test data, add SQL to: supabase/seed.sql"
echo "   then run: supabase db reset"
echo "──────────────────────────────────────"
