import {
  type RouteConfig,
  index,
  layout,
  prefix,
  route,
} from "@react-router/dev/routes";

export default [
  route("sitemap.xml", "routes/sitemap.ts"),
  route("robots.txt", "routes/robots.ts"),

  route("api/search", "routes/api/search.ts"),
  route("api/pricing", "routes/api/pricing.ts"),
  route("api/contact", "routes/api/contact.ts"),
  route("api/checkout", "routes/api/checkout.ts"),
  route("api/checkout/crypto", "routes/api/checkout-crypto.ts"),
  route("api/promote/activate", "routes/api/promote-activate.ts"),
  route("api/analytics/view", "routes/api/analytics-view.ts"),
  route("api/notifications/delete", "routes/api/notifications-delete.ts"),
  route("api/notify/price-drop", "routes/api/notify-price-drop.ts"),
  route("api/revalidate", "routes/api/revalidate.ts"),
  route("api/embeddings/sync", "routes/api/embeddings-sync.ts"),
  route("api/webhooks/stripe", "routes/api/webhooks-stripe.ts"),
  route("api/webhooks/coinbase", "routes/api/webhooks-coinbase.ts"),
  route("api/cron/expire-offers", "routes/api/cron-expire-offers.ts"),
  route("api/cron/expire-promotions", "routes/api/cron-expire-promotions.ts"),
  route("api/dealer/subscribe", "routes/api/dealer-subscribe.ts"),
  route("api/dealer/change-plan", "routes/api/dealer-change-plan.ts"),
  route("api/dealer/portal", "routes/api/dealer-portal.ts"),
  route("api/dealer/verify-session", "routes/api/dealer-verify-session.ts"),
  route("api/dealer/import-csv", "routes/api/dealer-import-csv.ts"),
  route("api/dealer/redeem-code", "routes/api/dealer-redeem-code.ts"),
  route("api/dealer/close-shop", "routes/api/dealer-close-shop.ts"),
  route("api/dealer/reopen-shop", "routes/api/dealer-reopen-shop.ts"),
  route("api/ai/autofill", "routes/api/ai-autofill.ts"),
  route("api/ai/describe", "routes/api/ai-describe.ts"),
  route("api/ai/insights", "routes/api/ai-insights.ts"),
  route("api/ai/pricing", "routes/api/ai-pricing.ts"),
  route("api/ai/search", "routes/api/ai-search.ts"),
  route("api/ai/shop-description", "routes/api/ai-shop-description.ts"),

  ...prefix(":locale", [
    layout("routes/locale-layout.tsx", [
      index("routes/home.tsx"),
      route("search", "routes/search.tsx"),
      route("listing/:slug", "routes/listing.tsx"),
      route("vehicles", "routes/vehicles.tsx"),
      route("properties", "routes/properties.tsx"),
      route("shops", "routes/shops.tsx"),
      route("shop/:slug", "routes/shop.tsx"),
      route("profile/:userId", "routes/profile.tsx"),
      route("pricing", "routes/pricing.tsx"),
      route("blog", "routes/blog.tsx"),
      route("blog/:slug", "routes/blog-slug.tsx"),
      route("about", "routes/about.tsx"),
      route("faq", "routes/faq.tsx"),
      route("how-it-works", "routes/how-it-works.tsx"),
      route("contact", "routes/contact.tsx"),
      route("terms", "routes/terms.tsx"),
      route("privacy", "routes/privacy.tsx"),
      route("cookies", "routes/cookies.tsx"),
      route("safety", "routes/safety.tsx"),
      route("compare", "routes/compare.tsx"),
      route("saved", "routes/saved.tsx"),
      route("auth/login", "routes/login.tsx"),
      route("auth/signup", "routes/signup.tsx"),
      route("auth/register", "routes/register-redirect.ts"),
      route("auth/forgot-password", "routes/forgot-password.tsx"),
      route("auth/callback", "routes/auth-callback.ts"),
      route("post", "routes/post.tsx"),
      route("onboarding", "routes/onboarding.tsx"),
      route("shop-onboarding", "routes/shop-onboarding.tsx"),
      route("promote/:id", "routes/promote.tsx"),
      route("promote/success", "routes/promote-success.tsx"),
      route("messages", "routes/messages-index.tsx"),
      route("messages/:id", "routes/messages-id.tsx"),
      route("admin/reports", "routes/admin-reports.tsx"),
      route("dashboard", "routes/dashboard-layout.tsx", [
        index("routes/dashboard/index.tsx"),
        route("listings", "routes/dashboard/listings.tsx"),
        route("settings", "routes/dashboard/settings.tsx"),
        route("saved", "routes/dashboard/saved.tsx"),
        route("saved-searches", "routes/dashboard/saved-searches.tsx"),
        route("purchases", "routes/dashboard/purchases.tsx"),
        route("notifications", "routes/dashboard/notifications.tsx"),
        route("messages", "routes/dashboard/messages.tsx"),
        route("messages/:id", "routes/dashboard/messages-id.tsx"),
        route("offers", "routes/dashboard/offers.tsx"),
        route("analytics", "routes/dashboard/analytics.tsx"),
        route("inventory", "routes/dashboard/inventory.tsx"),
        route("inventory/new", "routes/dashboard/inventory-new.tsx"),
        route("sales", "routes/dashboard/sales.tsx"),
        route("plan", "routes/dashboard/plan.tsx"),
        route("branding", "routes/dashboard/branding.tsx"),
        route("dealer", "routes/dashboard/dealer.tsx"),
        route("shop", "routes/dashboard/shop.tsx"),
        route("shop/offers", "routes/dashboard/shop-offers.tsx"),
        route("shop/inventory", "routes/dashboard/shop-inventory.tsx"),
        route("shop/branding", "routes/dashboard/shop-branding.tsx"),
        route("shop/analytics", "routes/dashboard/shop-analytics.tsx"),
        route("shop/sales", "routes/dashboard/shop-sales.tsx"),
        route("shop/messages", "routes/dashboard/shop-messages.tsx"),
        route("edit/:id", "routes/dashboard/edit.tsx"),
      ]),
    ]),
  ]),

  route("*", "routes/locale-redirect.ts"),
] satisfies RouteConfig;
