import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

/**
 * POST /api/dealer/import-csv
 *
 * Accepts a JSON body with an array of parsed listing rows from the client.
 * Validates each row, inserts them in bulk, and returns results.
 *
 * Only available to authenticated Pro Sellers.
 */

type ImportRow = {
  title: string;
  description?: string;
  price?: number | null;
  price_type?: string;
  condition?: string;
  category_slug?: string;
  subcategory_slug?: string;
  location_slug?: string;
  contact_phone?: string;
  attributes?: Record<string, string>;
};

type InsertResult = {
  row: number;
  status: "created" | "error";
  title: string;
  slug?: string;
  error?: string;
};

export async function POST(req: NextRequest) {
  try {
    const supabase = await createClient();

    // Verify auth
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Verify Pro Seller status
    const { data: profile } = await supabase
      .from("profiles")
      .select("is_pro_seller")
      .eq("id", user.id)
      .single();

    if (!profile?.is_pro_seller) {
      return NextResponse.json(
        { error: "Only Pro Sellers can bulk import listings" },
        { status: 403 },
      );
    }

    const body = await req.json();
    const rows: ImportRow[] = body.rows;

    if (!Array.isArray(rows) || rows.length === 0) {
      return NextResponse.json(
        { error: "No rows provided" },
        { status: 400 },
      );
    }

    if (rows.length > 200) {
      return NextResponse.json(
        { error: "Maximum 200 listings per import" },
        { status: 400 },
      );
    }

    // Fetch reference data for slug → id resolution
    const [{ data: categories }, { data: subcategories }, { data: locations }] =
      await Promise.all([
        supabase.from("categories").select("id, slug"),
        supabase.from("subcategories").select("id, slug, category_id"),
        supabase.from("locations").select("id, slug, name"),
      ]);

    const catMap = new Map(
      (categories ?? []).map((c) => [c.slug.toLowerCase(), c.id]),
    );
    const subMap = new Map(
      (subcategories ?? []).map((s) => [s.slug.toLowerCase(), s]),
    );
    const locMap = new Map(
      (locations ?? []).map((l) => [l.slug.toLowerCase(), l.id]),
    );
    // Also allow matching by location name
    const locNameMap = new Map(
      (locations ?? []).map((l) => [l.name.toLowerCase(), l.id]),
    );

    const results: InsertResult[] = [];

    for (let i = 0; i < rows.length; i++) {
      const row = rows[i];

      // Validate required fields
      if (!row.title || row.title.trim().length < 3) {
        results.push({
          row: i + 1,
          status: "error",
          title: row.title || "(empty)",
          error: "Title is required (min 3 characters)",
        });
        continue;
      }

      // Resolve category
      const catSlug = (row.category_slug ?? "").toLowerCase().trim();
      const categoryId = catMap.get(catSlug);
      if (!categoryId) {
        results.push({
          row: i + 1,
          status: "error",
          title: row.title,
          error: `Unknown category: "${row.category_slug}"`,
        });
        continue;
      }

      // Resolve subcategory (optional)
      let subcategoryId: string | null = null;
      if (row.subcategory_slug) {
        const subSlug = row.subcategory_slug.toLowerCase().trim();
        const sub = subMap.get(subSlug);
        if (sub && sub.category_id === categoryId) {
          subcategoryId = sub.id;
        }
      }

      // Resolve location (optional — try slug first, then name)
      let locationId: string | null = null;
      if (row.location_slug) {
        const locKey = row.location_slug.toLowerCase().trim();
        locationId =
          locMap.get(locKey) ?? locNameMap.get(locKey) ?? null;
      }

      // Build insert payload
      const insertPayload = {
        user_id: user.id,
        title: row.title.trim(),
        slug: "", // auto-generated by DB trigger
        description: row.description?.trim() || null,
        price:
          row.price !== undefined && row.price !== null
            ? Number(row.price)
            : null,
        price_type: row.price_type || "fixed",
        condition: row.condition || null,
        category_id: categoryId,
        subcategory_id: subcategoryId,
        location_id: locationId,
        contact_phone: row.contact_phone || null,
        status: "draft" as const,
        ...(row.attributes &&
        Object.values(row.attributes).some((v) => v?.trim())
          ? { attributes: row.attributes }
          : {}),
      };

      const { data, error } = await supabase
        .from("listings")
        .insert(insertPayload)
        .select("id, slug")
        .single();

      if (error) {
        results.push({
          row: i + 1,
          status: "error",
          title: row.title,
          error: error.message,
        });
      } else {
        results.push({
          row: i + 1,
          status: "created",
          title: row.title,
          slug: data.slug,
        });
      }
    }

    const created = results.filter((r) => r.status === "created").length;
    const errors = results.filter((r) => r.status === "error").length;

    return NextResponse.json({
      summary: { total: rows.length, created, errors },
      results,
    });
  } catch (err) {
    console.error("CSV import error:", err);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 },
    );
  }
}
